### ISSUE TITLE
Not able to add Youtube video

### ISSUE THREAD

**Issue by michaelhyppel** [blabbercut/Feedback-Issue-Reporting#1]
1. Load site
2. Paste URL to youtube video
https://www.youtube.com/watch?v=aatr_2MstrI
3. Title of video fetched as well as preview image
4. Cannot add video with Play icon, button/picture non clickable

Windows 10 Home, Swedish
Chrome Version 57.0.2987.98 (64-bit)

**Comment by andreasnaslund** [comment]
Just nu lägger den till klippet i slutet på grid men inget mer. Tanken är att den ska öppna klippet i spelaren direkt men har inte löst detta ännu. Vände på grid så senaste ligger längst upp tills det är löst.
